### ISSUE TITLE
License blacklist

### ISSUE THREAD

**Issue by rprieto** [jslicense/licensee.js#6] opened 2017-05-30 22:46 UTC
From the README and looking at https://npmjs.com/packages/spdx-expression-parse it's not clear whether we can have a license blacklist, e.g. `NOT GPL`.

This could be useful, especially for existing projects where creating and conforming to a whitelist could take some time. It could be simpler to start with "no GPL" (for example) and go from there.

**Comment by kemitchell** [comment] 2017-05-31 02:38
`licensee` does not currently support a blacklist, only an SPDX expression for approved licenses and a package-version whitelist.

I'm open to different experiences, but when I've seen rigorous license checks, they've almost always been whitelist-based.  Part of the issue is that a license-based blacklist doesn't save you much work when you're talking in terms of specific licenses, by SPDX identifier.  Which is what good `package.json` metadata does, and what we want to do when auditing.

Take your GPL example.  There are three versions of the GPL, as well as variants---LGPL, AGPL---in their own versions.  If what you're really concerned about is "copyleft", the GPL family alone doesn't cover it.  You also need to worry about MPL, EPL, OSL, and so on.  If you're just concerned about "strong copyleft", well, there's no standard definition or list of licenses for what comes in that category.

In the past, where I've used `licensee` for my own projects, I've often created an initial whitelist like so:

```shell
cd project
licensee | fgrep Terms: | cut -d ' ' -f 4- | fgrep -v Invalid | sort -u | tee list-of-licenses
```

That gives me some idea what I already have, so I can write a rule, run `licensee` again, and attend to any packages with invalid metadata.  Usually by reviewing them and whitelisting most.  When `licensee` passes, I check in the configuration , add an npm script to run it, and add the npm script to configuration for whatever CI service I may be using.  That way if I install a dependency with a license that isn't on the list yet, later, I'll see a failed build, and consider whether to add it to the rule.

If I build up a configuration for one project and start up a related project, I can reuse the config.

**Comment by rprieto** [comment] 2017-05-31 04:03
Thanks for the very quick reply! The comments about copy-left make sense. The workflow you describe sounds great, I will probably start using that for personal projects.

The use case I had in mind was scanning a very large number of repositories, and being able to know "do we depend on copyleft packages". For example: `notLicense: (GPL OR AGPL OR MPL OR EPL OR OSL)`. I understand your point of view though, so happy to use the whitelist approach instead.

**Comment by kemitchell** [comment] 2017-05-31 04:07
Thanks for your note.  I'll go ahead and close this one.

Just a quick tip in parting: Even the example you provided isn't a valid SPDX expression, since none of those strings are valid SPDX expressions.  You'll need to provide versions as well, like `GPL-3.0`.

**Closed by kemitchell** 2017-05-31 04:07 UTC
